### ISSUE TITLE
AppStore 审核被拒

### ISSUE THREAD

**Issue by JoshYuJump** [react-native-component/react-native-smart-amap-location#16]
ref: http://lbs.amap.com/dev/room?id=47&sa=a825e49fddf2cf9bc14ed957b192774b

The location SDK's lastest version is `2.4.0`

**Comment by microwin168** [comment]
请问，目前的这个版本修复这个问题了吗？

**Comment by JoshYuJump** [comment]
你可以用我的 fork 版

在 2017年6月5日，09:13，microwin168 <notifications@github.com<mailto:notifications@github.com>> 写道：


目前的这个版本修复这个问题了吗？
