### ISSUE TITLE
碰到个好像https的问题，来请教一下

### ISSUE THREAD

**Issue by 0x55aa** [react-native-component/react-native-smart-amap-location#5]
我用的ios10.1的模拟器，AMapLocation.getLocation()没问题。
AMapLocation.getReGeocode();就提示“错误代码9，服务器连接失败”
amap文档说是 “传输链路出现问题，请检查您的host是否正常”

我在配置高德 Key 前，添加开启 HTTPS 功能的代码
[[AMapServices sharedServices] setEnableHTTPS:YES];
应用启动的时候就闪退，这个可能会是什么原因呢，不太懂，希望给点建议啊。

**Comment by cyqresig** [comment]
该功能的调试请使用真机

**Comment by 0x55aa** [comment]
多谢啦
