### ISSUE TITLE
 Duplicate interface definition for class 'RCTBridge'

### ISSUE THREAD

**Issue by eriodesign** [react-native-component/react-native-smart-amap-location#8]
老师您好，按照ios配置步骤下来，运行发现 amap框架出现几个错误
分别是： 
**.../node_modules/react-native/React/Base/RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'**
以及连续几个：
**.../node_modules/react-native/React/Base/RCTBridge.h:154:55: Property has a previous declaration**
百忙之中希望您看到给予解答，谢谢！

**Comment by eriodesign** [comment]
当前环境：
"react-native": "0.40.0",
"react-native-smart-amap-location": "^1.1.1",
"platform":" iOS 10.2 on iPhone 7"

**Comment by eriodesign** [comment]
截图如下：
<img width="445" alt="screenshot 2017-01-11 13 52 55" src="https://cloud.githubusercontent.com/assets/1698325/21837302/0014be20-d806-11e6-9368-bf4d577657e1.png">

**Comment by cyqresig** [comment]
您好，react-native 0.40版本ios的类引用方式改了，故现在的带ios代码的插件都会存在问题:(，可以先用0.39版本试下

**Comment by JoshYuJump** [comment]
他升级到 `1.1.3` 应该就解决这个问题了，这个 issue 能够关闭啦 😄

**Comment by hkwin** [comment]
你好，假如是fetch-blob又应该如何解决咧？出现的是一样的问题，暂时除去react-native降级的方法，谢谢！图就不贴了，报的错误都是一样的。

"react-native": "0.44.3",
"react-native-fetch-blob": "github:wkh237/react-native-fetch-blob-package"
