### ISSUE TITLE
没有运行定位

### ISSUE THREAD

**Issue by zuzuviewer** [react-native-component/react-native-smart-amap-location#9]
在组件的componentDidMount方法中添加如下代码：
`componentDidMount(){
        // let viewAppearCallBack = (event) => {
        console.log('start main page componentDidMount');
        AMapLocation.init({
            onceLocation:false,
            allowsBackgroundLocationUpdates:true,
        }); //使用默认定位配置;
        DeviceEventEmitter.addListener('amap.location.onLocationResult',function (result) {
            console.log('location:',result);
        })
    }`
但是发现没有任何日志输出，后来在您的RCTAMapLocationModule中添加了输出语句，也没有输出：
` AMapLocationListener locationListener = new AMapLocationListener() {
        @Override
        public void onLocationChanged(AMapLocation location) {
        Log.i("amapmsg", "unknown");`
我已经在一开始就同意了软件卫星或网络定位权限，请问这是为何没有事件发出

**Comment by cyqresig** [comment]
请问您是什么版本的android系统

**Comment by zuzuviewer** [comment]
使用的红米NOTE,安卓版本为“5.1.1 LMY47V”,MIUI版本为“MIUI 8.0 稳定版”

**Comment by cyqresig** [comment]
版本应该没问题，是不是您高德定位sdk的key设置的不对？

**Comment by zuzuviewer** [comment]
key是直接从官网复制过来的，但是我刚才又检查了下，是一样的。另外key不对的话应该会返回错误，而不是什么都不输出吧

**Comment by zuzuviewer** [comment]
已经解决，是build.gradle里只配置了release版本的签名，没配置debug的，所以SHA1不一样
